version: "3"
services:
  openblocks:
    image: openblocksdev/openblocks-ce
    container_name: openblocks
    ports:
      - "3000:3000"
    volumes:
      - ./stacks:/openblocks-stacks
    restart: unless-stopped
